version: "3"

services:
  jenkins:
    image: jenkins/jenkins:lts
    restart: always
    volumes:
      - ${JENKINS_HOME}:/var/jenkins_home
      - /etc/localtime:/etc/localtime
    ports:
      - 8080:8080
      - 50000:50000

  gitlab:
    image: gitlab/gitlab-ce
    restart: always
    ports:
      - 80:80
      - 22:22
      - 443:443
    volumes:
      - ${GITLAB_HOME}/conf:/etc/gitlab
      - ${GITLAB_HOME}:/var/opt/gitlab
      - ${GITLAB_HOME}/log:/var/log/gitlab

  sonarqube:
    image: kennyallen/sonarqube:7.2.1
    restart: always
    ports:
      - 9000:9000
    volumes:
      - ${SONARQUBE_HOME}:/opt/sonarqube/data
