version: "3"

services:
  gitlab:
    image: gitlab/gitlab-ce
    restart: always
    ports:
      - 80:80
      - 22:22
      - 443:443
    volumes:
      - ${GITLAB_HOME}/conf:/etc/gitlab
      - ${GITLAB_HOME}:/var/opt/gitlab
      - ${GITLAB_HOME}/log:/var/log/gitlab
