version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node

  leon_elasticsearch-head:
    image: mobz/elasticsearch-head:5
    ports:
      - 9100:9100
    volumes:
      - /home/eilinge/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  leon_logstash:
    image: docker.elastic.co/logstash/logstash:6.2.4
    volumes:
      - ./logstash.yaml:/usr/share/logstash/config/logstash.yml
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ${LOGSTASH}/dataJson:/usr/local/

  leon_kibana:
    image: docker.elastic.co/kibana/kibana:7.5.0@sha256:0dfe7c796a7702556cd7e9bb7e2d56be335ec22260ce569038b3aaf663afa90b
    ports:
       - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://192.168.1.180:9200
