version: "3"

services:
  jenkins:
    image: jenkins/jenkins:lts
    restart: always
    volumes:
      - ${JENKINS_HOME}:/var/jenkins_home
      - /etc/localtime:/etc/localtime
    ports:
      - 8080:8080
      - 50000:50000
