global:
  scrape_interval:     60s
  evaluation_interval: 60s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
        labels:
          instance: prometheus

  - job_name: linux
    static_configs:
      - targets: ['172.19.37.39:9100']
        labels:
          instance: localhost
  - job_name: internal
    static_configs:
      - targets: ['47.101.187.227:9100']
        labels:
          instance: internal
      
